# Start AeroSpace at login
start-at-login = false

# Enable janky borders with sapphire color
after-startup-command = [
  'exec-and-forget borders active_color=0xff7dc4e4 inactive_color=0xff494d64 width=8.0',
]

accordion-padding = 32

[gaps]
inner.horizontal = 16
inner.vertical = 16
outer.left = 16
outer.bottom = 16
outer.top = 16
outer.right = 16

[mode.main.binding]
# Disable macos keymaps
cmd-m = [] # Disable "minimize application"

# These keymaps create the workspaces on startup
alt-k = 'workspace k' # kitty
alt-b = 'workspace b' # browser
alt-i = 'workspace i' # ai
alt-m = 'workspace m' # misc

# Move window to workspace
alt-shift-k = ['move-node-to-workspace k', 'workspace k']
alt-shift-b = ['move-node-to-workspace b', 'workspace b']
alt-shift-i = ['move-node-to-workspace i', 'workspace i']
alt-shift-m = ['move-node-to-workspace m', 'workspace m']

# Change focus in workspace
alt-h = 'focus left'
alt-l = 'focus right'

# Move window within workspace
alt-shift-h = 'move left'
alt-shift-l = 'move right'

# Toggle between accordion & tiles
alt-slash = 'layout accordion tiles'

# Focus other monitor
alt-enter = ['focus-monitor --wrap-around next']

# Move window to other monitor
alt-shift-enter = [
  'move-node-to-monitor --wrap-around next',
  'focus-monitor --wrap-around next',
]

# Move kitty to workspace k
[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace k'

# Move Arc browser to workspace b
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = 'move-node-to-workspace b'

# Move ChatGPT to workspace i
[[on-window-detected]]
if.app-id = 'com.openai.chat'
run = 'move-node-to-workspace i'

# Move Spotify to workspace m
[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace m'

# Move DBeaver to workspace m
[[on-window-detected]]
if.app-id = 'org.jkiss.dbeaver.core.product'
run = 'move-node-to-workspace m'

# Move LibreOffice to workspace m
[[on-window-detected]]
if.app-id = 'org.libreoffice.script'
run = 'move-node-to-workspace m'

# Float calendar
[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'layout floating'

# Float reminders
[[on-window-detected]]
if.app-id = 'com.apple.reminders'
run = 'layout floating'

# Float system settings
[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'
