# Start AeroSpace at login
start-at-login = true

# Enable janky borders with flamingo color
after-startup-command = [
  'exec-and-forget borders active_color=0xfff0c6c6 inactive_color=0xff494d64 width=5.0',
]

[gaps]
inner.horizontal = 16
inner.vertical =   16
outer.left =       16
outer.bottom =     16
outer.top =        16
outer.right =      16

[mode.main.binding]
# These mappings create the workspaces on startup
alt-i = 'workspace 1'
alt-u = 'workspace 1' # typo safety because alt-u performs undo in nvim
alt-o = 'workspace 2'
alt-p = 'workspace 3'

# Focus window
alt-leftSquareBracket = 'focus left'
alt-rightSquareBracket = 'focus right'

# Move window
alt-shift-leftSquareBracket = 'move left'
alt-shift-rightSquareBracket = 'move right'

# Move window to workspace
alt-shift-i = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-o = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-p = ['move-node-to-workspace 3', 'workspace 3']

# Move node to other monitor
ctrl-alt-cmd-left = ['move-node-to-monitor --wrap-around prev',  'focus-monitor --wrap-around prev']
ctrl-alt-cmd-right = ['move-node-to-monitor --wrap-around next',  'focus-monitor --wrap-around next']

# Open apps
# k = kitty, b = arc, c = calendar, r = reminders
alt-k = 'exec-and-forget open -a "Kitty"'
alt-b = 'exec-and-forget open -a "Arc"'
alt-r = 'exec-and-forget open -a "Reminders"'
alt-c = 'exec-and-forget open -a "Calendar"'

# Focus other monitor
alt-m = 'focus-monitor --wrap-around next'

# Toggle between accordion & tiles
alt-comma = 'layout accordion tiles'

# Move kitty to workspace 1
[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = ['move-node-to-workspace 1']

# Move Arc to workspace 2
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = ['move-node-to-workspace 2']
