# Start AeroSpace at login
start-at-login = true

# Enable sketchybar and janky borders with sapphire color
after-startup-command = [
  'exec-and-forget sketchybar',
  'exec-and-forget borders active_color=0xff7dc4e4 inactive_color=0xff494d64 width=8.0',
]

exec-on-workspace-change = ['/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

[gaps]
inner.horizontal = 16
inner.vertical =   16
outer.left =       16
outer.bottom =     16
outer.top =        56
outer.right =      16

# ======================= MAIN MODE
[mode.main.binding]
# Overrides
cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"


# These mappings create the workspaces on startup, so there will only be 4.
# A fifth will be created when using a second monitor.
# In a lot of browsers, cmd-1/2/3/4 moves to tab 1/2/3/4. But in Arc I never use this.
cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'

# Change focus in workspace
alt-comma = 'focus left'
alt-period = 'focus right'

# Focus other display
alt-d = 'focus-monitor --wrap-around next'

# Enter move mode
alt-m = 'mode move'

# Toggle between accordion & tiles
alt-slash = 'layout accordion tiles'
# ======================= END MAIN MODE

# It's preferable to have a single mode because you need less key presses.
# However, these actions do not occur often and it's hard to find bindings that
# do not conflict with vim or macos.
# ======================= MOVE MODE
[mode.move.binding]
# Move window to workspace
1 = ['move-node-to-workspace 1', 'workspace 1', 'mode main']
2 = ['move-node-to-workspace 2', 'workspace 2', 'mode main']
3 = ['move-node-to-workspace 3', 'workspace 3', 'mode main']
4 = ['move-node-to-workspace 4', 'workspace 4', 'mode main']

# Move window in the same workspace
h = ['move left', 'mode main']
l = ['move right', 'mode main']

# Move window to other monitor
shift-h = ['move-node-to-monitor --wrap-around next',  'focus-monitor --wrap-around next', 'mode main']
shift-l = ['move-node-to-monitor --wrap-around prev',  'focus-monitor --wrap-around prev', 'mode main']

# Switch to main mode
esc = 'mode main'
enter = 'mode main'
alt-m = 'mode main'
# ======================= END MOVE MODE

# Move kitty to workspace 1
[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = ['move-node-to-workspace 1']

# Move Arc browser to workspace 2
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = ['move-node-to-workspace 2']

# Move all other apps to workspace 3
[[on-window-detected]]
if.app-name-regex-substring = '^(?!.*\b(net\.kovidgoyal\.kitty|company\.thebrowser\.Browser)\b).*'
run = ['move-node-to-workspace 3']
