# Start AeroSpace at login
start-at-login = true

# Enable janky borders with flamingo color
after-startup-command = [
  'exec-and-forget borders active_color=0xfff0c6c6 inactive_color=0xff494d64 width=5.0',
]

[gaps]
inner.horizontal = 16
inner.vertical =   16
outer.left =       16
outer.bottom =     16
outer.top =        16
outer.right =      16

[mode.main.binding]
# [ and ] mappings are for switching between workspaces & nodes in a workspace
# Switch between workspaces with <Alt-[> and <Alt-]>
alt-leftSquareBracket = 'workspace prev --wrap-around'
alt-rightSquareBracket = 'workspace next --wrap-around'
# Move focus in workspace with <Alt-Shift-]> and <alt-shift-]>
alt-shift-leftSquareBracket = 'focus left'
alt-shift-rightSquareBracket = 'focus right'

# H/L mappings are for moving node to different workspace/monitor
# Move node to other workspace
alt-shift-h = 'move-node-to-workspace prev --wrap-around'
alt-shift-l = 'move-node-to-workspace next --wrap-around'
# Move node to other monitor
ctrl-alt-cmd-h = ['move-node-to-monitor --wrap-around prev',  'focus-monitor --wrap-around next']
ctrl-alt-cmd-l = ['move-node-to-monitor --wrap-around next',  'focus-monitor --wrap-around next']

# Open apps
# k = kitty, b = arc, c = calendar, r = reminders
alt-k = 'exec-and-forget open -a "Kitty"'
alt-b = 'exec-and-forget open -a "Arc"'
alt-r = 'exec-and-forget open -a "Reminders"'
alt-c = 'exec-and-forget open -a "Calendar"'

# Focus other monitor
alt-m = 'focus-monitor --wrap-around next'

# Toggle between accordion & tiles
alt-comma = 'layout accordion tiles'

# These mappings are needed to create the workspaces on startup
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'

# Move kitty to workspace 1
[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = ['move-node-to-workspace 1']

# Move Arc to workspace 2
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = ['move-node-to-workspace 2']
