format = """
$python\
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

[directory]
style = "green"
truncate_to_repo = false
truncation_length = 10

[character]
success_symbol = "[❯](white)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "blue"

[git_status]
format = " [[(*$conflicted$untracked$modified$staged$renamed$deleted)](218)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"

# add virtal env on separate line
[python]
format = "($virtualenv($style)\n)"
style = "white"
