require("rimai/plugin-setup")

require("rimai/keymaps")
require("rimai/options")
require("rimai/colorscheme")
require("rimai/commands")

require("rimai/plugins/telescope")
require("rimai/plugins/treesitter")
require("rimai/plugins/bufferline")
require("rimai/plugins/gitsigns")
require("rimai/plugins/lualine")
require("rimai/plugins/lsp")
require("rimai/plugins/null-ls")
require("rimai/plugins/neo-tree")
require("rimai/plugins/autopairs")
require("rimai/plugins/toggleterm")
require("rimai/plugins/typescript")
